<?php
/**
 * Set background for:
 * Home page
 * Category default
 * Category custom
 * Product page
 * CMS page 
 * 
 */


$currentPlace = Mage::helper('setbackground')->getCurrentPlace();
//echo $currentPlace;

$model = Mage::getModel('catalog/category');
$categories = $model->getCollection()->addAttributeToSelect('*')->addIsActiveFilter()->addLevelFilter(2);
$configImage = $this->getConfigImage();
$attachment = '';
$repeat = '';
if(isset($configImage)){
    if($configImage['repeat-x'] == 1 AND $configImage['repeat-y'] == 1) $repeat = 'repeat';
    elseif($configImage['repeat-x'] == 1 AND $configImage['repeat-y'] == 0) $repeat = 'repeat-x';
    elseif($configImage['repeat-x'] == 0 AND $configImage['repeat-y'] == 1) $repeat = 'repeat-y';
    else $repeat = 'no-repeat';
    
    $attachment = $configImage['attachment'];
    $zindex = $configImage['z-index'];
}

//if($this->getConfigImage()) print 'true';
//else print 'false';

?>

<?php if (Mage::getStoreConfig('setbackground/info/enabled')): ?>

        <?php //$_background = $this->getBackground(); ?>
        <?php $_background_items = $this->getBackgroundItem($currentPlace); ?>

        <?php foreach ($_background_items as $_background_item): ?>                           
            <?php if ($_background_item->getItem_id() == $currentPlace): ?>
                <div id="setbackground"></div>
                <style>
                    #setbackground {
                        background: url("<?php echo Mage::getBaseUrl('media') . $_background_item->getImage() ?>") <?php echo $repeat . ' ' . $attachment ?>  0 0 transparent;
                        z-index: <?php echo $zindex ?>;
                    }
                </style>                   
            <?php endif; ?>                   
        <?php endforeach; ?>
                    
<?php endif;?>

